apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Annynetwork/continious_integration.git
    targetRevision: HEAD
    path: kubernetes-jenkins
  
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
   
    automated:
      selfHeal: true
      prune: true
    